name: Build Java Project

on:
  push:
    branches: 
      - "master"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: mvn compile
      - run: mvn package

      - name: Install WiX Toolset
        run: dotnet tool install wix --global --version 5.0.2

      - name: Add WiX Extension
        run: wix extension add --global WixToolset.Util.wixext/5.0.2

      - name: Package with jpackage (Windows)
        shell: cmd
        run: |
          jpackage ^
            --type exe ^
            --input target ^
            --dest build_output ^
            --name ntousi_MemoryGame ^
            --main-jar MemoryGame-1.0-SNAPSHOT.jar ^
            --main-class de.bbq.memorygame.MainApp ^
            --win-menu ^
            --win-shortcut ^
            --win-per-user-install ^
            --win-dir-chooser

      - uses: actions/upload-artifact@v4
        with:
          name: ntousi_MemoryGame-Windows.exe
          path: build_output/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'
          cache: maven

      - run: sudo apt-get update
      - run: sudo apt-get install -y fakeroot binutils dpkg

      - run: mvn compile
      - run: mvn package

      - name: Package with jpackage (Linux)
        run: |
          jpackage \
            --type deb \
            --input target \
            --dest build_output \
            --name ntousi_MemoryGame \
            --main-jar MemoryGame-1.0-SNAPSHOT.jar \
            --main-class de.bbq.memorygame.MainApp

      - uses: actions/upload-artifact@v4
        with:
          name: ntousi_MemoryGame-Linux.deb
          path: build_output/*.deb

  release:
    runs-on: ubuntu-latest
    needs: [build-windows, build-linux]
    permissions:
      contents: write
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ntousi_MemoryGame-Windows
          path: build_output

      - uses: actions/download-artifact@v4
        with:
          name: ntousi_MemoryGame-Linux
          path: build_output

      - id: version
        run: echo "version=$(date +v%Y.%m.%d-%H%M%S)" >> "$GITHUB_OUTPUT"

      - uses: ncipollo/release-action@v1
        with:
          artifacts: build_output/*.exe,build_output/*.deb
          tag: ${{ steps.version.outputs.version }}
