name: Build Java Project

on:
  push:
    branches: 
      - "master"

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Create build_output folder
        run: mkdir build_output

      - name: Package with jpackage (Windows)
        run: |
          jpackage ^
            --type exe ^
            --input target ^
            --dest build_output ^
            --name ntousi_MemoryGame ^
            --main-jar MemoryGame-1.0-SNAPSHOT.jar ^
            --main-class de.bbq.memorygame.MainApp ^
            --win-menu ^
            --win-shortcut ^
            --win-per-user-install ^
            --win-dir-chooser

      - name: Upload Windows Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ntousi_MemoryGame-Windows
          path: build_output/*.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'zulu'
          cache: maven

      - name: Install jpackage dependencies
        run: sudo apt-get update && sudo apt-get install -y libfreetype6 fakeroot

      - name: Build JAR with Maven
        run: mvn clean package

      - name: Create build_output folder
        run: mkdir build_output

      - name: Package with jpackage (Linux)
        run: |
          jpackage \
            --type deb \
            --input target \
            --dest build_output \
            --name ntousi_MemoryGame \
            --main-jar MemoryGame-1.0-SNAPSHOT.jar \
            --main-class de.bbq.memorygame.MainApp

      - name: Upload Linux Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ntousi_MemoryGame-Linux
          path: build_output/*.deb

  release:
    runs-on: ubuntu-latest
    needs: [build-linux, build-windows]
    permissions:
      contents: write

    steps:
      - uses: actions/download-artifact@v4
        with:
          name: ntousi_MemoryGame-Windows
          path: build_output

      - uses: actions/download-artifact@v4
        with:
          name: ntousi_MemoryGame-Linux
          path: build_output

      - name: Show files
        run: ls -la build_output

      - id: version
        run: echo "version=$(date +v%Y.%m.%d-%H%M%S)" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: build_output/*.exe,build_output/*.deb
          tag: ${{ steps.version.outputs.version }}
